### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MrDiamond64** [snaildos/SnailMiner#3]
Video: https://streamable.com/1lx103

Once i enter my user ID the miner crashes

Notes:
- My antivirus is disabled
- Am using integrated graphics (may be the cause?)

**Comment by MrDiamond64** [comment]
also for whatever reason when i paste my user ID theres a bunch of spaces after the last character

**Comment by snaildos** [comment]
Hello,
Thanks for using SnailDOS and creating a issue,
Regaeding your problem, just a follow up, follow these steps and try again.
1) disable windows defender too.
2) delete the xmrig folder in downloads.
3) attempt to run again.
Hopefully these will fix your issues.
Also, watching the video shows that you lasted your I'd and deleted some numbers, ensure the ID is correct. We are working on resolving the pasting glitch. Thank you!

**Comment by MrDiamond64** [comment]
Alright, I have tried the miner again with all your suggestions and realized that the miner only works on NVIDIA graphics card (intel graphics do not have cuda cores). Thanks for your help.

**Comment by snaildos** [comment]
My bad, I thought you where using the CPU miner.
Great to hear it's resolved.
